### PR TITLE
Exposes tint and shade functions

### PR DESCRIPTION
**Pull request by nathanbowser**

### CODE REVIEW

**Review by derekstory — APPROVED** [review]
Cool, is this for a specific issue? Just curious of the specific use case. +1

**Comment by nathanbowser** [comment]
@derekstory Yep. These functions exist in the chart project and I now need them for the new shapes component. Once this is merged I'll write an issue in the chart project to remove its functions and use these.

**Comment by nathanbowser** [comment]
@derekstory Also see https://github.com/SpiderStrategies/Scoreboard/issues/55552

**Comment by mattsgarlata** [comment]
+1

**Pull request merged**
