### PR TITLE
V6 non color palette updates

### PR DESCRIPTION
**Pull request by derekstory**
I had originally branched off the v6 branch, but I think that was a bad choice. It will probably be easier to just commit directly to it so that I can update the hash in Impact each time so its always up to date with the color changes. 

@mattsgarlata @nathanbowser Mind if I merge this PR into the V6 branch and just commit directly to that after this?

### CODE REVIEW

**Comment by mattsgarlata** [comment]
I think we still need to do PRs so that we can do code reviews.

Would it work to use the latest commit hash from your branch and then update the hash after the scoreboard-color changes have been merged in?

**Comment by mattsgarlata** [comment]
+1

**Comment by mattsgarlata** [comment]
@nathanbowser do you want to review simple changes like this, or would it be better for me to just merge them in? I can always wait for your review on more complex changes.

@derekstory do you want to maintain the commit history here, or should I squash the commits before merging this in?

**Comment by derekstory** [comment]
@mattsgarlata I see what's going on now. I **thought** I was getting errors trying to use the hash from the last commit of this branch because it needed to be in the main v6 branch for it to work. 

But within **Impact**, just updating **package.json** with the latest hash didn't work because the old hash was referenced a few times in package-lock.json. Manually replacing the hash in **package-lock.json** works (let me know if there's a better approach to that).

I can just leave this open for now and mark it as a draft since its working now. Also, I don't think there will be any complex changes to scoreboard-colors. Mostly just updating values.

**Comment by mattsgarlata** [comment]
After updating `package.json` you need to run `npm i` and that will update `package-lock.json`.

Let's talk over this via a huddle.

**Comment by mattsgarlata** [comment]
@nathanbowser we weren't able to get `npm i` to update `package-lock.json` correctly, so @derekstory could use your help with that when you get back.

@derekstory why is this a draft again? This should be ready to merge in, right?

**Comment by derekstory** [comment]
@mattsgarlata I'll unmark it as draft at the end of the day if that's okay.

**Comment by derekstory** [comment]
Actually, I don't think it matters. Ready.

**Comment by mattsgarlata** [comment]
Thanks! Since Nathan is on vacation, I think I’ll just go ahead and merge this in. If there’s something he’d like to change, we can open a new PR.

@derekstory do you want the commits maintained or squashed?

**Comment by derekstory** [comment]
Squashed is good with me.

**Comment by nathanbowser** [comment]
@derekstory If you run 'npm i scoreboard-colors-v6@github:SpiderStrategies/scoreboard-colors#NEWHASH' it should update both the package and package lock. 

Just updating package.json manually and running 'npm I' won't work bc that installs from the package lock (which is the whole point of it)

Let me know if that still doesn't work and I can take a look when I'm back on a computer.

**Comment by derekstory** [comment]
@nathanbowser Still getting the same thing where it says its an invalid version and is using the hash value thats in package-lock.json. 


```
MacBook-Pro:static derekstory$ npm i scoreboard-colors-v6@github:SpiderStrategies/scoreboard-colors#329ec7c9a00bb49df76a70c494ef73dd7425c51a
npm ERR! Invalid Version: git+ssh://git@github.com/SpiderStrategies/scoreboard-colors.git#735555464f5cdc39820e2447f3877b4c172ad823

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/derekstory/.npm/_logs/2024-01-25T17_36_45_116Z-debug-0.log
```

It's no rush though. I've got a work around.

**Comment by nathanbowser** [comment]
I think you're running into issues b/c `735555464f5cdc39820e2447f3877b4c172ad823` is a commit that doesn't exist in scoreboard-colors.

When using hashes for npm dependencies, we have to make sure those commits exist in the repo, so a branch is deleted that had the commit, history is reworked (ie squash, rebase, etc), that commit might disappear.

```
~/dev/scoreboard/scoreboard-colors master
❯ git branch --contains
```

@derekstory I can probably clean up the Impact side of things, ping me when you're free and we can walk through it together.

**Pull request merged**
