### PR TITLE
for SpiderStrategies/Scoreboard#46757 update with new score colors

### PR DESCRIPTION
**Pull request by jerryorr**

### CODE REVIEW

**Comment by mattsgarlata** [comment]
It doesn't seem like there's a difference between chart series colors and score colors anymore, so perhaps we should do away with the synonymous names and just call them like `$color-red-medium` or just `$red-medium`. What do you think?

@derekstory your thoughts would also be appreciated

**Comment by jerryorr** [comment]
We could probably combine them, though that will probably require us to update a few more places (like the chart and gauge projects). I'm not sure if they 100% overlap, though. Could definitely use @derekstory's input.

**Comment by nathanbowser** [comment]
@jerryorr In a lot of projects, I'm doing this: https://github.com/SpiderStrategies/chart/blob/master/style/chart.scss#L5

I've been wondering if we can combine all the colors. 

That said, this whole scoreboard-colors might be getting a major overhaul soon based on a conversation I had yesterday with Scott.

**Comment by jerryorr** [comment]
Also, we probably still need some sort of SASS array that gives all the colors that could be in a chart/gauge/bubble/etc, like `$score-colors` and `$chart-series-colors` do right now. We iterate over those arrays to build relevant styles in Scoreboard. Any thoughts on a generic name for that combined array?

**Comment by mattsgarlata** [comment]
Another option is to just merge this PR in the way it is now, and then plan to do a larger revamp of the colors later. Potentially after we figure out how we're supporting continuous colors (#46606)

**Comment by jerryorr** [comment]
That'd be my preference; probably better to have someone other than me making big changes to our colors.

**Comment by mattsgarlata** [comment]
Sounds good. Any objection @derekstory @nathanbowser?

**Comment by nathanbowser** [comment]
No objections, I think that's a good plan considering big changes are coming.

My only concern would be the removal of some variables. e.g. `$score-red:`. But if other projects (gauges, charts, etc) are referencing those variables directly, we'll know pretty quickly.

**Comment by jerryorr** [comment]
I do have some corresponding changes in Scoreboard, but no other projects broke, as far as I could tell. I _think_ the Scoreboard SASS compilation would have failed.

**Review by derekstory — APPROVED** [review]

**Comment by mattsgarlata** [comment]
OK, I'll merge this in. Thanks everyone!

**Pull request merged**
